language: node_js

addons:
  sauce_connect: true

before_script:
  - npm i -g bower
  - bower i
  - npm run update-webdriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run test-travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
